"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e*h==ss1t#=0e%i#_v%kc$)8sk-+#c&tp$6uu2y+2ezo)n+h0@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # timetable first — its admin/login.html overrides unfold's login
    'timetable',
    # unfold must come before django.contrib.admin to override admin templates
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# ------------------------------------------------------------
# django-unfold admin theme
# ------------------------------------------------------------
from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": "SmartTimetable",
    "SITE_HEADER": "SmartTimetable Admin",
    "SITE_SUBHEADER": "Timetable Scheduling System",
    "SITE_URL": "/timetable/setup/",
    "SITE_ICON": None,
    "SITE_SYMBOL": "calendar_today",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "STYLES": [
        lambda request: static("timetable/css/admin_extra.css"),
    ],
    "COLORS": {
        "primary": {
            "50":  "238 242 255",
            "100": "224 231 255",
            "200": "199 210 254",
            "300": "165 180 252",
            "400": "129 140 248",
            "500": "99  102 241",
            "600": "79  70  229",
            "700": "67  56  202",
            "800": "55  48  163",
            "900": "49  46  129",
            "950": "30  27  75",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Timetable",
                "separator": True,
                "items": [
                    {"title": "Setup (Departments)", "icon": "settings",     "link": "/admin/timetable/setupmodel/"},
                    {"title": "Teachers",            "icon": "person",       "link": "/admin/timetable/teachermodel/"},
                    {"title": "Class Rooms",         "icon": "meeting_room", "link": "/admin/timetable/classroommodel/"},
                    {"title": "Lab Rooms",           "icon": "science",      "link": "/admin/timetable/labroommodel/"},
                    {"title": "Recess Times",        "icon": "coffee",       "link": "/admin/timetable/recessmodel/"},
                    {"title": "Years",               "icon": "school",       "link": "/admin/timetable/yearsetupmodel/"},
                    {"title": "Year Classrooms",     "icon": "door_front",   "link": "/admin/timetable/yearclassroommodel/"},
                    {"title": "Year Lab Rooms",      "icon": "biotech",      "link": "/admin/timetable/yearlabroommodel/"},
                    {"title": "Saved Timetables",    "icon": "table_view",   "link": "/admin/timetable/departmenttimetablemodel/"},
                ],
            },
            {
                "title": "Auth & Users",
                "separator": True,
                "items": [
                    {"title": "Users",  "icon": "manage_accounts", "link": "/admin/auth/user/"},
                    {"title": "Groups", "icon": "group",           "link": "/admin/auth/group/"},
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Require login for all timetable pages
    'timetable.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'project_name.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_name.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/timetable/setup/'   # after login, go to first real app page
LOGOUT_REDIRECT_URL = '/accounts/login/'

# URLs that do NOT require login (home page is public)
LOGIN_EXEMPT_URLS = [
    '/',              # root redirect
    '/timetable/',    # timetable root redirect
    '/timetable/home/',  # public landing page
]

# Teacher workload thresholds (hours per week)
# Customise these to suit your department's norms.
TEACHER_WORKLOAD_MIN = 10        # Below this = underutilised
TEACHER_WORKLOAD_MAX = 30        # Above this = overloaded
TEACHER_WORKLOAD_IDEAL_MIN = 15  # Ideal lower bound
TEACHER_WORKLOAD_IDEAL_MAX = 25  # Ideal upper bound
