# Generated by Django 5.2.3 on 2026-01-18 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_rename_departmentname_setupmodel_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupmodel',
            name='hours_in_lecture',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setupmodel',
            name='hours_in_practical',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setupmodel',
            name='number_of_days',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='classRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=100)),
                ('classroom_capacity', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_classRooms', to='timetable.setupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='labRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labroom_id', models.CharField(max_length=100)),
                ('labroom_capacity', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_labRooms', to='timetable.setupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_teachers', to='timetable.setupmodel')),
            ],
        ),
    ]
