# Generated by Django 5.2.10 on 2026-01-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_setupmodel_hours_in_lecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedNameClassRooms', to='timetable.setupmodel'),
        ),
        migrations.AlterField(
            model_name='labroommodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedNameLabRooms', to='timetable.setupmodel'),
        ),
        migrations.AlterField(
            model_name='setupmodel',
            name='hours_in_lecture',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setupmodel',
            name='hours_in_practical',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedNameTeachers', to='timetable.setupmodel'),
        ),
        migrations.CreateModel(
            name='recessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recess_start_time', models.TimeField()),
                ('recess_end_time', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedNameRecesses', to='timetable.setupmodel')),
            ],
        ),
    ]
