# Generated by Django 5.2.10 on 2026-01-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_classroommodel_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yearSetupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField()),
                ('number_of_students_in_batch', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedNameYearSetupModel', to='timetable.setupmodel')),
            ],
        ),
    ]
