# Generated by Django 5.2.10 on 2026-01-23 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_yearsetupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('teachers', models.ManyToManyField(to='timetable.teachermodel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetable.yearsetupmodel')),
            ],
        ),
    ]
