# Generated by Django 5.2.10 on 2026-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_subjectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
