# Generated by Django 5.2.10 on 2026-01-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_subjectmodel_hours_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='practicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_name', models.CharField(max_length=100)),
                ('hours_per_week', models.PositiveIntegerField()),
                ('teachers', models.ManyToManyField(to='timetable.teachermodel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicals', to='timetable.yearsetupmodel')),
            ],
        ),
    ]
