# Generated by Django 5.2.10 on 2026-01-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_practicalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='yearClassRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classrooms', models.ManyToManyField(to='timetable.classroommodel')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yearClassRoomsAllocated', to='timetable.yearsetupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='yearLabRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labrooms', models.ManyToManyField(to='timetable.labroommodel')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yearLabRoomsAllocated', to='timetable.yearsetupmodel')),
            ],
        ),
    ]
