# Generated by Django 5.2.10 on 2026-02-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_yearclassroommodel_yearlabroommodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTimetableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('displayTimetable', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realatedNameSavedTimetablesOfDepartment', to='timetable.setupmodel')),
            ],
        ),
    ]
