# Generated by Django 5.2.10 on 2026-02-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_departmenttimetablemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttimetablemodel',
            name='lectureHoursTable',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='departmenttimetablemodel',
            name='practicalHoursTable',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='departmenttimetablemodel',
            name='teacherYearChart',
            field=models.JSONField(default=dict),
        ),
    ]
