# Generated by Django 5.2.10 on 2026-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_departmenttimetablemodel_lecturehourstable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttimetablemodel',
            name='fitness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
